# Generated by Django 4.2.4 on 2023-08-09 13:05
import phonenumbers
from django.db import migrations


def normalize_phone_number(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    for flat in flats.iterator():
        parse_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        pure_phonenumber = phonenumbers.format_number(
            parse_phonenumber,
            phonenumbers.PhoneNumberFormat.E164,
            )
        flat.owner_pure_phone = pure_phonenumber
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_number),
    ]
