# Generated by Django 4.2.4 on 2023-08-09 14:14

from django.db import migrations
from property.models import Owner


def fill_owners_name_and_phone(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    for flat in flats.iterator():
        Owner.objects.get_or_create(owner=flat.owner,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_flat_owner_pure_phone_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owners_name_and_phone),
    ]
