# Generated by Django 4.2.4 on 2023-08-10 08:16

from django.db import migrations


def fill_owners_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        owner, _ = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone)
        owner.flats.add(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20230809_1814'),
    ]

    operations = [
        migrations.RunPython(fill_owners_flats),
    ]
