# Generated by Django 4.2.4 on 2023-08-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_rename_owner_owner_name_alter_complaint_flat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
